## list of Ten Zeros

In [2]:
import numpy

In [2]:
numpy.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

## List of Numbers from ten to 49

In [5]:
numpy.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [8]:
numpy.arange(4)

array([0, 1, 2, 3])

## Matrix with integer and float

In [10]:
numpy.ones([2,3], dtype=numpy.int)

<ipython-input-10-1925360202cf>:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  numpy.ones([2,3], dtype=numpy.int)


array([[1, 1, 1],
       [1, 1, 1]])

In [13]:
z= numpy.ones([2,3], dtype=numpy.float)
z

<ipython-input-13-e1b55c635d40>:1: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  z= numpy.ones([2,3], dtype=numpy.float)


array([[1., 1., 1.],
       [1., 1., 1.]])

In [21]:
z[:,:2]

array([[1., 1.],
       [1., 1.]])

In [30]:
X = numpy.arange(4, dtype=numpy.int)
numpy.ones_like(X)


<ipython-input-30-3d06d80972a5>:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  X = numpy.arange(4, dtype=numpy.int)


array([1, 1, 1, 1])

In [31]:
numpy.ones([4,4], dtype=numpy.int) * 5

<ipython-input-31-79f7e95eeaf4>:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  numpy.ones([4,4], dtype=numpy.int) * 5


array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [32]:
numpy.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [36]:
x= numpy.identity(5)
numpy.ones_like(x)*7

array([[7., 7., 7., 7., 7.],
       [7., 7., 7., 7., 7.],
       [7., 7., 7., 7., 7.],
       [7., 7., 7., 7., 7.],
       [7., 7., 7., 7., 7.]])

In [43]:
numpy.random.randint(10, size=3)

array([3, 5, 8])

In [42]:
numpy.random.randint(10, size=[3,3])

array([[7, 0, 2],
       [2, 4, 2],
       [3, 4, 0]])

In [50]:
numpy.random.randn(3,3,3)

array([[[-0.83102073, -1.57962518, -0.49771925],
        [-1.50798677,  0.74216256,  1.43984465],
        [-1.50203598, -1.07431961, -0.72726471]],

       [[ 0.62050724, -2.13554439,  0.53811842],
        [ 1.33754369, -1.25698129, -0.10384757],
        [-0.28577555,  0.97199649,  1.56108863]],

       [[-0.99506907,  1.02944979, -0.61798934],
        [-0.79303268,  0.28333621, -0.28675181],
        [-0.48075553,  1.16238239, -0.20050207]]])

In [51]:
X = [1, 2, 3]
print(X, type(X))

Y = numpy.array(X)
print(Y, type(Y))

[1, 2, 3] <class 'list'>
[1 2 3] <class 'numpy.ndarray'>


In [55]:
X = numpy.array([5,2,3], dtype=numpy.float)
print(X, id(X))

Y = numpy.copy(X)
print(Y, id(Y))

[5. 2. 3.] 3141213434000
[5. 2. 3.] 3141213437456


<ipython-input-55-8d89d7a8bf47>:1: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  X = numpy.array([5,2,3], dtype=numpy.float)


In [63]:
numpy.arange(1, 11, 2)


array([1, 3, 5, 7, 9])

In [70]:
numpy.arange(1, 11)[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [4]:
numpy.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [72]:
X = numpy.array(['A','B','C','D','E'])

X[0:3]

array(['A', 'B', 'C'], dtype='<U1')

In [74]:
X[::2]

array(['A', 'C', 'E'], dtype='<U1')

In [75]:
X[::-1]

array(['E', 'D', 'C', 'B', 'A'], dtype='<U1')

In [76]:
numpy.arange(1,10)[::2]

array([1, 3, 5, 7, 9])

In [83]:
X = numpy.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X[-1, -1] = 0
X

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15,  0]])

In [82]:
X = [0, 10, -5, 40, -3]

X.sort()
X

[-5, -3, 0, 10, 40]

In [85]:
X = numpy.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X + 5


array([[ 6,  7,  8,  9],
       [10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

In [86]:
X = numpy.array([-1,2,0,-4,5,6,0,0,-9,10])

mask = X <= 0
mask

array([ True, False,  True,  True, False, False,  True,  True,  True,
       False])

In [89]:
X = numpy.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])

mask = X > 5
X[mask]

array([ 6, 10])

In [90]:
X = numpy.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])

mask = (X == 2) | (X == 10)
X[mask]

array([ 2, 10])

In [91]:
X = numpy.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])

X.all()

False

In [92]:
X = numpy.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])

X.any()

True

In [94]:
X = numpy.array([1, 2, 0, 4, 5, 6, 0, 0, 9, 10])

#np.mean(X)
numpy.mean(X)

3.7

In [95]:
X = numpy.array([1, 2, 0, 4, 5, 6, 0, 0, 9, 10])

#np.mean(X)
X.mean()

3.7

## Axis=1 is rows and Axis=0 is columns

In [98]:
X = numpy.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

numpy.sum(X, axis=0)

array([28, 32, 36, 40])

In [100]:
X = numpy.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

numpy.sum(X, axis=1)

array([10, 26, 42, 58])

## OR



In [99]:
X = numpy.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])
X.sum(axis=0)

array([28, 32, 36, 40])

In [101]:
X = numpy.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])
X.sum(axis=1)

array([10, 26, 42, 58])

## Useful numpy functions
### [arange, random, eye, identity, reshape, linspace, zeros, ones, empty]

In [105]:
numpy.random.random(size=2)



array([0.98369872, 0.64501459])

In [103]:
numpy.random.normal(size=2)

array([-0.28983128,  0.30724726])

In [104]:
numpy.random.rand(2, 4)

array([[0.83842264, 0.00399029, 0.28413997, 0.18073148],
       [0.29758579, 0.35571221, 0.67415987, 0.79474043]])

In [106]:
numpy.arange(5, 10)

array([5, 6, 7, 8, 9])

In [107]:
numpy.arange(0, 1, .1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [108]:
numpy.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [109]:
numpy.empty(5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [113]:
numpy.eye(3, 3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [114]:
numpy.eye(8, 4, k=1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [115]:
"Hello World"[6]

'W'